### PR TITLE
Governance APIs for the Delta Sharing Server

### PR DESCRIPTION
**Pull request by wchau**
This is still a draft in progress. The idea is to have APIs based off of the Databricks Unity Catalog APIs.

### CODE REVIEW

**Comment by wchau** [comment]
> What's the context? and what would it be used for?

The context is that there have been multiple requests to not use a static config file, so instead, we want to give a simple option to allow SQL-backed management APIs

**Comment by samgriek-arc** [comment]
Is anyone pushing this forward?  This would be super handy for my use case.

**Comment by chakankardb** [comment]
@wchau Is this still a draft?

**Comment by linzhou-db** [comment]
closing as it's stale.

**Pull request closed without merging**
